In [1]:
import numpy as np

In [ ]:
#1 Create a null vector of size 10 but the fifth value which is 1.

In [45]:
Vec1 = np.zeros(10)
Vec1[4] = 1
print(Vec1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# Q2Create a vector with values ranging from 10 to 49.

In [47]:
vector2 = np.arange(10,50)
print(vector2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Q3 Create a 3x3 matrix with values ranging from 0 to 8

In [52]:
mat1 = np.random.randint(0,8,(3,3))
mat1

array([[3, 1, 1],
       [2, 5, 1],
       [1, 0, 7]])

In [54]:
#4 Find indices of non-zero elements from [1,2,0,0,4,0]


In [56]:
x = np.nonzero([1,2,0,0,4,0])
x

(array([0, 1, 4], dtype=int64),)

In [ ]:
#5 Create a 10x10 array with random values and find the minimum and maximum values.

In [77]:
b = np.random.randn(10,10)
print(b)
print("maximum value",np.max(b))
print("minimum value",np.min(b))

[[-0.10301992 -0.94756594  0.78456709 -0.47888514  0.71601672  0.08219918
  -2.04651999  0.90146752  0.74728562  0.91353114]
 [ 1.50642732  0.08922276  0.37339599 -0.8360846  -0.14864181 -0.74506596
   1.30694806 -1.17335232  0.03957975  0.93178222]
 [ 0.66584153 -1.33149998 -0.19063308  0.04490831 -1.01920184 -2.17446932
   0.08357195  0.05439464  1.99593663 -0.4761989 ]
 [-0.30395875  1.46331685 -0.80128896  1.39428694 -0.18404136 -2.07841167
  -0.81424816  1.4847497   1.54063504 -0.67623329]
 [ 1.07986448 -1.24148402  0.06317297 -1.13845528 -0.1937689   0.76537057
   1.38009259 -1.25068706  0.35870272 -0.79203498]
 [ 1.72812721  0.72092984  0.3226881  -0.05783498 -0.4454294  -0.75175827
  -1.13716278  0.40136751  0.83383552  0.69517649]
 [ 0.85380677 -1.54428958  0.52052152 -0.12930442 -1.29950129  0.49255707
  -0.01443448 -1.03753343 -1.39771626  0.0236852 ]
 [-0.06387651  1.41152479  1.26226346 -0.05103514  0.94025283  1.78128982
  -0.80638492  2.06409483 -0.40101194 -1.5922882 ]


In [78]:
#6 Create a random vector of size 30 and find the mean value.

In [70]:
x = np.random.rand(30)
print(x)
x.mean()

[0.59283793 0.3542203  0.09959397 0.13936373 0.99425904 0.729358
 0.85639664 0.16728259 0.82295702 0.38635005 0.98684142 0.49495087
 0.12274171 0.67816906 0.56002424 0.42957558 0.72504158 0.91911215
 0.22246432 0.85579087 0.23354732 0.33745659 0.81684634 0.42004691
 0.17441589 0.9145157  0.84037297 0.59934788 0.60587948 0.00222665]


0.5360662263182369